esphome:
  name: espnow-gateway-test
  friendly_name: ESPNOW Gateway test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espnow-Gateway-Test"
    password: "J4viLcG9bUmb"

#ESPNow - section from here 
sensor:
  - platform: template
    name: "ESPNow Temperature"
    id: espnow_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - platform: template
    name: "ESPNow Humidity"
    id: espnow_hum
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: template
    name: "ESPNow Pressure"
    id: espnow_pres
    unit_of_measurement: "hPa"
    accuracy_decimals: 0
  - platform: template
    name: "ESPNow Battery"
    id: espnow_batt
    unit_of_measurement: "%"
    accuracy_decimals: 0

#ESPNow stuff
espnow:
  id: espnow_component
  auto_add_peer: true 
  peers:                   # Optional
    - "34:85:18:00:2D:E4"  # altan-sensor-1 mac address

  on_broadcast:
    - logger.log:
        format: "BROADCAST - Sent to %s from %s: %s RSSI: %ddBm"
        args:
          - format_mac_address_pretty(info.des_addr).c_str()
          - format_mac_address_pretty(info.src_addr).c_str()
          - format_hex_pretty(data, size).c_str()
          - info.rx_ctrl->rssi

  on_unknown_peer:
    - logger.log:
        format: "UNKNOWN Peer !! Sent to %s from %s: %s RSSI: %ddBm"
        args:
          - format_mac_address_pretty(info.des_addr).c_str()
          - format_mac_address_pretty(info.src_addr).c_str()
          - format_hex_pretty(data, size).c_str()
          - info.rx_ctrl->rssi

  on_receive:
    - lambda: |-
        ESP_LOGD("espnow", "Received %d bytes from %s", size, format_hex_pretty(info.src_addr, 6).c_str());
        std::string hex_data = format_hex_pretty(data, size).c_str();
        ESP_LOGD("espnow", "Raw data: %s", hex_data.c_str());

        // Define the struct to match your sender
        struct sensorData {
          char senderID[11];
          int type;
          float temp;
          float humi;
          int pres;
          int batt;
        };
        
        // Check if we received enough data
        if (size >= sizeof(sensorData)) {
          sensorData receivedData;
          memcpy(&receivedData, data, sizeof(sensorData));
          
          // Null-terminate the senderID to be safe
          receivedData.senderID[10] = '\0';
          
          // Log the received data
          ESP_LOGD("espnow", "Sender ID: %s", receivedData.senderID);
          ESP_LOGD("espnow", "Type: %d", receivedData.type);
          ESP_LOGD("espnow", "Temp: %.1f°C", receivedData.temp);
          ESP_LOGD("espnow", "Humidity: %.1f%%", receivedData.humi);
          ESP_LOGD("espnow", "Pressure: %d mBar", receivedData.pres);
          ESP_LOGD("espnow", "Battery: %d%%", receivedData.batt);

          // Publish to sensors
          //TODO: Condition if more than one Sensor this pict the right one 
          id(espnow_temp).publish_state(receivedData.temp);
          id(espnow_hum).publish_state(receivedData.humi);
          id(espnow_pres).publish_state(receivedData.pres);
          id(espnow_batt).publish_state(receivedData.batt);
        } else {
          ESP_LOGW("espnow", "Received data too small: %d bytes", size);
        }
         




    